### ISSUE TITLE
Cannot find t5-base model

### ISSUE THREAD

**Issue by JueXiuHuang** [luyaojie/Text2Event#8]
Hi,
I met problem when executing the training script `bash run_seq2seq_verbose.bash -d 0 -f tree -m t5-base --label_smoothing 0 -l 1e-4 --lr_scheduler linear --warmup_steps 2000 -b 16
` , how can I solve this problem? 
Below is the error message

> 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/t5-base-pytorch_model.bin
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1030, in from_pretrained
>     resolved_archive_file = cached_path(
>   File "/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py", line 1134, in cached_path
>     output_path = get_from_cache(
>   File "/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py", line 1300, in get_from_cache
>     r.raise_for_status()
>   File "/opt/conda/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/t5-base-pytorch_model.bin
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "run_seq2seq.py", line 750, in <module>
>     main()
>   File "run_seq2seq.py", line 399, in main
>     model = AutoModelForSeq2SeqLM.from_pretrained(
>   File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/modeling_auto.py", line 1301, in from_pretrained
>     return MODEL_FOR_SEQ_TO_SEQ_CAUSAL_LM_MAPPING[type(config)].from_pretrained(
>   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1046, in from_pretrained
>     raise EnvironmentError(msg)
> OSError: Can't load weights for 't5-base'. Make sure that:
> 
> - 't5-base' is a correct model identifier listed on 'https://huggingface.co/models'
> 
> - or 't5-base' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

**Comment by JueXiuHuang** [comment]
It seems that I can't access the tuna mirror and thus I cant download t5-base model.
After remove `mirror='tuna'` from file `run_seq2seq.py` in line 406, everything is OK! (❁´◡`❁)
